

runtime:
  steps: 20000
  save_fig: "H13_sustainable_population.png"
  dpi: 180
  style: "seaborn-v0_8"
  save_metrics: "H13_sustainable_population.npz"
  seed: 123

sizes:
  R: 16
  G: 24
  J: 12
  N: 200000
  k_latent: 4

trade:
  k_neighbors: 8
  alpha_logistics_ex: 0.06
  alpha_logistics_sink: 0.0020

markets:
  tau: 0.12
  beta_aff: 2.4

time:
  demurrage: 0.010
  dt: 1.0

duals:
  eta_ex: 0.02
  eta_sink: 0.08
  util_target: 0.15 
  mu_floor: 0.010
  mu_cap: 1.0e10
  lambda_floor: 0.040
  lambda_cap: 1.0e10
  mu0: 0.020
  lambda0: 0.070
  ema_ex: 0.90
  ema_sink: 0.90 

scaling:
  gen_scale: 0.85
  storage_scale: 1.10
  sink_cap_scale: 0.04
  sink_intensity_scale: 10.0
  gen_sink_intensity_scale: 1.0
  gen_noise: 0.20

environment:
  sink_assim_rate: 1e-3

policy:
  aec_low: 0.82
  aec_high: 0.93
  ers_k: 9.0
  gate_min: 0.15
  gate_k: 20.0
  aec_init: 0.88

extraction:
  n_resources: 4
  k_ext: 0.25
  beta_ext: 3.0
  xi_ext0: 1.2
  sig_ext0: 0.9
  dep_alpha_xi: 1.2
  dep_alpha_sig: 1.5
  reserves_scale: 8000000.0

demography:
  pop_init_scale: 1200000.0
  working_age: 18
  retirement_age: 65
  female_share: 0.50
  adult_gomp_alpha: 4.2e-5
  adult_gomp_beta: 0.085
  adult_makeham_lambda: 5.0e-4
  imr_base: 0.025
  u5_child_base: 0.0010
  youth_base: 2.0e-4
  eta_neonatal: 2.5
  eta_child: 2.0
  eta_adult: 1.0
  mort_sink_mult: 0.6
  fert_theta_dev: 0.5
  fert_phi_rep: 0.2
  fert_theta_cyc: 0.8
  birth_endow_atp: 0.10
  birth_endow_fiat: 5.0

inheritance:
  inherit_conc: 2.0
  inherit_frac_on_death: 0.90

behavior:
  greed_tau_scale: 0.60
  save_base: 0.035
  save_greed_scale: 0.05
  invest_innov_base: 0.22
  invest_innov_greed_scale: 0.25
  invest_storage_base: 0.12
  invest_storage_greed_scale: 0.10

innovation:
  eta_innov: 0.0090
  innov_alpha: 0.85
  innov_spill: 0.0030
  innov_decay: 0.0005
  beta_xi: 1.10
  beta_sigma: 3.0
  beta_kcat: 0.70

investment:
  eta_storage: 0.00100
  storage_decay: 0.00010

engine:
  xi_floor: 1.0e-8
  sigma_floor: 1.0e-8
  softmax_temp_sigma: 0.40
  cap_innov_exergy_mult: 30.0
  cap_storage_exergy_mult: 20.0
  innov_I_cap: 1.0e9

migration:
  migration_rate_annual: 0.075
  migration_kappa: 1.25
