# configs/H6_financial_instability.yaml
# HYPOTHESIS 6: Weak financial regulation will cause Minsky-like boom-bust cycles, even with abundant resources.

runtime:
  steps: 20000
  plot: "final"
  save_fig: "H6_financial_instability.png"
  dpi: 180
  style: "seaborn-v0_8"
  save_metrics: "H6_financial_instability.npz"
  seed: 0

sizes:
  R: 16
  G: 24
  J: 12
  N: 200000
  k_latent: 4

trade:
  k_neighbors: 8
  alpha_logistics_ex: 0.08
  alpha_logistics_sink: 0.005

markets:
  tau: 0.15
  beta_aff: 2.0

time:
  demurrage: 0.008
  dt: 1.0

duals:
  eta_ex: 0.01
  eta_sink: 0.012
  util_target: 0.50
  mu_floor: 0.005
  mu_cap: 1000000.0
  lambda_floor: 0.02
  lambda_cap: 1000000.0
  mu0: 0.02
  lambda0: 0.05
  ema_ex: 0.90
  ema_sink: 0.90

scaling:
  # KEY CHANGE: Abundant energy to ensure constraint is financial
  gen_scale: 0.80
  storage_scale: 0.60
  # ---
  sink_cap_scale: 0.15
  sink_intensity_scale: 4.0
  gen_noise: 0.25

environment:
  sink_assim_rate: 0.01

policy:
  # KEY CHANGE: Weakened macroprudential policy
  aec_low: 0.60
  aec_high: 0.98
  ers_k: 6.0
  gate_min: 0.08
  gate_k: 4.0
  # ---
  aec_init: 0.86

extraction:
  n_resources: 4
  k_ext: 0.25
  beta_ext: 3.0
  xi_ext0: 1.2
  sig_ext0: 0.7
  dep_alpha_xi: 1.1
  dep_alpha_sig: 1.3
  reserves_scale: 8000000.0

demography:
  pop_init_scale: 1200000.0
  birth_base: 0.012
  death_base: 0.010
  aec_birth_center: 0.82
  aec_death_center: 0.50
  birth_k: 6.0
  death_k: 8.0
  birth_endow_atp: 0.10
  birth_endow_fiat: 5.0

inheritance:
  inherit_conc: 2.0
  inherit_frac_on_death: 0.90

behavior:
  greed_tau_scale: 0.50
  save_base: 0.06
  save_greed_scale: 0.10
  invest_innov_base: 0.04
  invest_innov_greed_scale: 0.06
  invest_storage_base: 0.02
  invest_storage_greed_scale: 0.04

innovation:
  eta_innov: 0.0012
  innov_alpha: 0.9
  innov_spill: 0.0015
  innov_decay: 0.0008
  beta_xi: 0.45
  beta_sigma: 0.55
  beta_kcat: 0.35

investment:
  eta_storage: 0.00015
  storage_decay: 0.0002
