# configs/H9_extreme_pressure_decoupled.yaml
# PURPOSE: Robust, decoupled growth under severe environmental pressure.
# IDEA: Early, firm λ → rapid σ melt via heavy innovation → λ normalizes; storage keeps μ low.

runtime:
  steps: 20000
  plot: "final"
  save_fig: "H9_extreme_pressure_decoupled.png"
  dpi: 180
  style: "seaborn-v0_8"
  save_metrics: "H9_extreme_pressure_decoupled.npz"
  seed: 0

sizes:
  R: 16
  G: 24
  J: 12
  N: 200000
  k_latent: 4

trade:
  k_neighbors: 14
  alpha_logistics_ex: 0.06
  alpha_logistics_sink: 0.0015

markets:
  tau: 0.10
  beta_aff: 2.6

time:
  demurrage: 0.009
  dt: 1.0

duals:
  eta_ex: 0.015
  eta_sink: 0.065          # less gain than H8 to damp pulses
  util_target: 0.12        # controller “aims” lower utilization
  mu_floor: 0.005
  mu_cap: 1000000.0
  lambda_floor: 0.040
  lambda_cap: 1000000.0
  mu0: 0.030
  lambda0: 0.080
  ema_ex: 0.86
  ema_sink: 0.93           # more smoothing to prevent overshoot

scaling:
  gen_scale: 0.85          # ample primary energy
  storage_scale: 1.10      # strong initial storage
  sink_cap_scale: 0.02     # extremely tight sinks
  sink_intensity_scale: 12.0
  gen_noise: 0.20

environment:
  sink_assim_rate: 0.0025  # slow natural regeneration

policy:
  aec_low: 0.82
  aec_high: 0.93
  ers_k: 9.0
  gate_min: 0.17
  gate_k: 20.0
  aec_init: 0.88

extraction:
  n_resources: 4
  k_ext: 0.25
  beta_ext: 3.0
  xi_ext0: 1.2
  sig_ext0: 0.9
  dep_alpha_xi: 1.2
  dep_alpha_sig: 1.5
  reserves_scale: 8000000.0

demography:
  pop_init_scale: 1200000.0
  birth_base: 0.012
  death_base: 0.010
  aec_birth_center: 0.82
  aec_death_center: 0.50
  birth_k: 6.0
  death_k: 8.0
  birth_endow_atp: 0.10
  birth_endow_fiat: 5.0

inheritance:
  inherit_conc: 2.0
  inherit_frac_on_death: 0.90

behavior:
  greed_tau_scale: 0.60
  save_base: 0.035
  save_greed_scale: 0.06
  invest_innov_base: 0.15
  invest_innov_greed_scale: 0.20
  invest_storage_base: 0.08
  invest_storage_greed_scale: 0.10

innovation:
  eta_innov: 0.0120        # faster T accumulation
  innov_alpha: 0.82        # mild concavity
  innov_spill: 0.0040      # faster diffusion
  innov_decay: 0.0004
  beta_xi: 1.35
  beta_sigma: 2.40         # rapid σ melt
  beta_kcat: 0.75

investment:
  eta_storage: 0.00160     # storage builds quickly
  storage_decay: 0.00008
